/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HotelGUI;

import javax.swing.JOptionPane;
import GeneratingBill.GeneratingCustomerBill;

/**
 *
 * @author hazeemhussain
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hotelMenuHeader = new javax.swing.JLabel();
        checkinButton = new javax.swing.JButton();
        roomsAvailableButton = new javax.swing.JButton();
        checkOutButton = new javax.swing.JButton();
        totalBillButton = new javax.swing.JButton();
        closebutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hotelMenuHeader.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        hotelMenuHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hotelMenuHeader.setText("HOTEL MENU");

        checkinButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        checkinButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Check in button.png"))); // NOI18N
        checkinButton.setText("CHECK-IN");
        checkinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkinButtonActionPerformed(evt);
            }
        });

        roomsAvailableButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        roomsAvailableButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Rooms Button.png"))); // NOI18N
        roomsAvailableButton.setText("ROOMS AVAILABLE");
        roomsAvailableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomsAvailableButtonActionPerformed(evt);
            }
        });

        checkOutButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        checkOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Check out button.png"))); // NOI18N
        checkOutButton.setText("CHECK-OUT");
        checkOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutButtonActionPerformed(evt);
            }
        });

        totalBillButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        totalBillButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Bill Button.png"))); // NOI18N
        totalBillButton.setText("CUSTOMERS BILL");
        totalBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBillButtonActionPerformed(evt);
            }
        });

        closebutton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        closebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Close Button.png"))); // NOI18N
        closebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .addComponent(hotelMenuHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addComponent(closebutton)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalBillButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(314, 314, 314)
                            .addComponent(roomsAvailableButton))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(350, 350, 350)
                            .addComponent(checkinButton))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(342, 342, 342)
                            .addComponent(checkOutButton))))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(closebutton)
                    .addComponent(hotelMenuHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(roomsAvailableButton)
                .addGap(52, 52, 52)
                .addComponent(checkinButton)
                .addGap(52, 52, 52)
                .addComponent(checkOutButton)
                .addGap(51, 51, 51)
                .addComponent(totalBillButton)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebuttonActionPerformed
        // TODO add your handling code here:
        //Closes the program if user clicks this button
        int close = JOptionPane.showConfirmDialog(null, "Are you sure you want to close the program?", "Select", JOptionPane.YES_NO_OPTION);
        if (close == 0) {
            System.exit(0);
        }
        
    }//GEN-LAST:event_closebuttonActionPerformed

    private void roomsAvailableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomsAvailableButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Rooms().setVisible(true);
    }//GEN-LAST:event_roomsAvailableButtonActionPerformed

    private void checkinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkinButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Checkin().setVisible(true);
    }//GEN-LAST:event_checkinButtonActionPerformed

    private void checkOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Checkout().setVisible(true);
    }//GEN-LAST:event_checkOutButtonActionPerformed

    private void totalBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBillButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Totalbill().setVisible(true);
    }//GEN-LAST:event_totalBillButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Menu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkOutButton;
    private javax.swing.JButton checkinButton;
    private javax.swing.JButton closebutton;
    private javax.swing.JLabel hotelMenuHeader;
    private javax.swing.JButton roomsAvailableButton;
    private javax.swing.JButton totalBillButton;
    // End of variables declaration//GEN-END:variables
}
